### ISSUE TITLE
[feat] 윈도우 환경에서 발생하는 eslint 에러 해결

### ISSUE THREAD

**Issue by naranghae** [jiphyeonjeon-42/backend#10]
윈도우 환경에서 eslint가 적용될 때 
` Expected linebreaks to be 'LF' but found 'CRLF'  ` 에러표시를 없애기 위해 .eslintrc.json에서 rules를 적용 하였습니다.
    "rules": {
        "linebreak-style": ["error", "windows"]
    }

**Comment by evelon** [comment]
#11 로 닫힙니다.
