### ISSUE TITLE
REFACT: TypeORM 적용

### ISSUE THREAD

**Issue by nyj001012** [jiphyeonjeon-42/backend#250]
### Likes
- [x] POST  /api/books/info/{bookInfoId}/like
- [x] DELETE /api/books/info/{bookInfoId}/like
- [x] GET /api/books/info/{bookInfoId}/like

### Reviews
- [x] POST /api/reviews
- [x] GET /api/reviews
- [x] PATCH /api/reviews/{reviewsId}
- [x] DELETE /api/reviews/{reviewsId}

**Comment by OverRaddit** [comment]
수정사항입니다!
- Likes기능에서 Where() 함수로 조건을 주는 부분에서 2개 이상의 조건을 and로 연결하는 방식이 잘못되어 해당 부분 수정하였습니다.
- entity파일을 모든 테이블마다 작성했습니다.

**Comment by OverRaddit** [comment]
TypeORM 자료를 찾아보던중 DB에 이미 존재하는 테이블을 토대로 entity파일을 생성해주는 패키지를 발견했습니다.
https://www.npmjs.com/package/typeorm-model-generator

<img width="1199" alt="스크린샷 2022-11-18 오전 11 05 51" src="https://user-images.githubusercontent.com/30787477/202600355-3294eb8b-a642-42af-9bd2-48ffab3b9717.png">

기존에 외래키를 가지는 테이블을 객체로 나타낼때, 외래키값을 그대로 Column에 raw값으로 저장해두는데 반해 (좌측부코드)
위 패키지로 생성한 entity파일은 JoinColumn과 ManyToOne같은 어노테이션을 사용합니다.(우측부코드)
객체가 다른 객체를 가리키는 참조관계를 JoinColumn으로 나타내고 일대일,일대다,다대일과 같은 관계를 ManyToOne으로 나타낸거죠!

이렇게 객체간의 참조관계를 나타내면 Service에서 Join하지 않고 객체를 사용할 수 있습니다
물론 일부만 Join하는 기존방식에서 객체 전체를 Join하기 때문에 성능은 떨어지지만 코드는 매우 가벼워 질 것 같습니다

한줄요약

> **/src/typeorm-entity/entities에 typeorm-model-generator 패키지로 entity파일을 생성하고 푸쉬해두었습니다.**

다음 회의때 한번더 말씀드리겠지만 관심있는 분들 미리 확인해보셔요 ㅎㅎ

**Comment by YeonSeong-Lee** [comment]
성능저하가 우려됨. -> 하지만 그냥 개발 편의를 위해 도입하기로 함.
-> 멘토링때 여쭤보기.

**Comment by nyj001012** [comment]
도입하기로 결정! 이후 RTF 팀에서 작업
