### ISSUE TITLE
REFACT: reveiw query builder로 되어 있는 부분 수정

### ISSUE THREAD

**Issue by YeonSeong-Lee** [jiphyeonjeon-42/backend#327]
query builder 로 되어있는 부분을 typeorm 기본 기능을 사용하여 리팩토링

**Comment by OverRaddit** [comment]
# 왜 복잡한 조건문 쿼리는 select query를 써야하는가?

A & B & C 라는 조건을 붙인다고 치자.
B라는 조건은 B1 || B2로 이루어져 있따.

그러면 이렇게된다.

A & (B1 || B2) & C

다만 저런 표기법은 불가능하다.
And조건으로 나뉜 조건들을 or로 나눌 수 없다.

그렇지만 반대는 가능하다.

(A & C & B1) ||  (A & C & B2)

or로 나뉜 조건들 사이에서는 and가 가능하다.
다만 B조건의 선택지가 현재 2개지만 여러개라면? 만약 5개라면?
그리고 A조건도 사실 선택지가 여러개라면?

경우의 수는 카티션 프러덕트가 된다.

또한 동적쿼리를 만드는 기존의 방식에서,,

userId인자가 api왜 함께 날아온경우
userId를 검색조건에 넣는다.

날아오지 않은경우
userId를 검색조건에 넣지 않는다.

typeorm상으로 날아오지 않은 인자를 처리할때 경우가 애매해진다.
특히 boolean의 경우 true,false값 모두를 가져올 방법이 해당 필드를 명시하지 않는방법밖에없는데,
동적쿼리방식이 아니기때문에 필드명시를 안할수가 없다.

굳이 find option으로 쓰려면 서비스로직을 옵션별로 나눠서 만들어야 하는데,
그 함수를 일일히 서비스로직으로 만든다는게 비효율적임.

차라리 복잡한 조건의 경우 셀렉트갓리빌더를 쓰는게 좋음.

상소문 끝
🚀
