### ISSUE TITLE
swagger 명세 정리

### ISSUE THREAD

**Issue by jimin52** [jiphyeonjeon-42/backend#358]
### 제안 사항
reservation api 명세가 일치하지 않는 상황이 발견되었습니다. 전체적으로 swagger 점검이 필요한것 같습니다.

### Todo
api 명세 점검하기
- [ ] reservation
- [ ] book
- [ ] user
- [ ] lending
- [ ] bookinfo
- [ ] like
- [ ] histories
- [ ] review
- [ ] stock api 명세 생성하기

**Comment by scarf005** [comment]
[@ts-rest/open-api](https://ts-rest.com/docs/open-api) 사용으로 자동화 가능할 것 같습니다
