### ISSUE TITLE
[BUG] Error: Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by YeonSeong-Lee** [jiphyeonjeon-42/backend#381]
wait_timeout을 일주일로 늘려서 임시로 문제를 해결

아래코드를 database 도커 이미지에 접속해서 root권한으로 실행시킴
```
set global wait_timeout=624800; 
```

->

2023.03.02 22:00시 근본적인 문제 해결로 롤백함

**Comment by OverRaddit** [comment]
명시적인 queryRunner 생성을 해주는 다른 entity repository(history, review) 또한 같은 방식으로 수정하였습니다.
