### ISSUE TITLE
검색창에 undefined 검색 시 전체 도서가 나옵니다.

### ISSUE THREAD

**Issue by chanhihi** [jiphyeonjeon-42/backend#443]
### 재현 방법

https://42library.kr/search?search=undefined&page=1

### 발생 위치

https://42library.kr/search?search=undefined&page=1

### 추가 정보

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/85754295/233370733-cbbff2e1-43e5-48e0-9a76-b6aea239ac09.png">

**Comment by scarf005** [comment]
## 문제 발생 원인

https://github.com/jiphyeonjeon-42/backend/blob/a8bbfdfe9f312973bfbbac64443d0f4d3b544c7d/backend/src/books/books.controller.ts#L93

request 검증 로직에서는 입력받은 검색 문자열을 `String()` 생성자로 파싱한 뒤, 결과값이 `'undefined'`라면 입력 오류로 판단하고 전체 검색을 하게 됩니다. 이때 `undefined` 원시값과 `"undefined"` 문자열 모두 `String` 생성자로 생성한 값이 `"undefined"`이기 때문에 문자열 `"undefined"`를 입력으로 받아도 결과값이 삼항 연산자의 `''`가 되어 전체 검색을 하게 됩니다.

```ts
> for (const value of [1, '문자열', '', 'undefined', { a: 1 }, null, undefined]) {
        console.log(`<${value}>: <${String(value)}>`)
}
<1>: <1>
<문자열>: <문자열>
<>: <>
<undefined>: <undefined>
<[object Object]>: <[object Object]>
<null>: <null>
<undefined>: <undefined>
```

## 해결 방법
직접 `req.query.query`의 값이 undefined인지 여부를 확인하면 해결할 수 있을 것 같습니다.
