### ISSUE TITLE
ErrorResponse 반환시 에러사유 추가

### ISSUE THREAD

**Issue by OverRaddit** [jiphyeonjeon-42/backend#444]
### 기능 설명

ErrorResponse를 반환할때, 에러 코드에 해당하는 에러 사유를 'id'필드에 추가합니다.

**Comment by jimin52** [comment]
오래된 이슈이고 진행사항이 없는 것으로 보임. 차후 Error 객체 리팩토링 할 때 따로 이슈를 열기로 합시다.
