### ISSUE TITLE
sub태그 default태그로 머지 시도시 실종됨

### ISSUE THREAD

**Issue by not-using** [jiphyeonjeon-42/backend#491]
### 재현 방법

1. PATCH tags/1024/merge { subTag: [125], superTagId: null } 로 요청 => 성공
2. GET tags/1024 에서는 추가된 디폴트태그가 보이지 않음
(처음 조회했던 GET tags/6/sub 에서도 사라짐)

### 추가 정보

![Jun-05-2023 20-51-43](https://github.com/jiphyeonjeon-42/backend/assets/74622889/2a28575b-b707-40f2-a844-fcecfbde39ee)

**Comment by not-using** [comment]
추가적으로 하위태그가 사라진 supter 태그는 없어지는 것 아니었나요?
이 부분은 기획방향이 헷갈려서 확인차 여쭤봅니다!

**Comment by nyj001012** [comment]
@notusing11 슈퍼 태그 삭제 시에 슈퍼 태그의 하위 태그가 없을 경우에만 삭제가 가능하고, 병합 시에 하위 태그가 사라진 슈퍼 태그에 대한 처리는 의논을 해보지 않았네요... 그래도 일단은 병합 중에 하위 태그가 사라져도 상위 태그는 살아있어야 하지 않을까요?
