### ISSUE TITLE
reviews/my-reviews GET 요청 인자 체크 오류

### ISSUE THREAD

**Issue by not-using** [jiphyeonjeon-42/backend#546]
### 재현 방법

1. reviews/my-reviews?limit=5&page=0&isMyReview=true GET 요청
2. 400 에러 errorCode 2 반환
3. 현재 배포 버전에서는 동일한 파라미터로 200 응답 성공

프론트 네트워크 요청은 변경된 점이 없는데 400에러로 바뀌었습니다. 

### 추가 정보

<img width="818" alt="image" src="https://github.com/jiphyeonjeon-42/backend/assets/74622889/017f4ed2-850c-49d0-b4a4-46675fc926ef">

**Comment by scarf005** [comment]
#539 와 연관있는것 같아요. 찾아주셔서 감사합니다! 혹시 GET 외에 다른 CRUD 작업에서도 똑같이 오류가 발생하였나요?

**Comment by not-using** [comment]
> #539 와 연관있는것 같아요. 찾아주셔서 감사합니다! 혹시 GET 외에 다른 CRUD 작업에서도 똑같이 오류가 발생하였나요

POST 요청이랑 UPDATE(사서권한 비공개요청) 성공 확인했습니다~ 
다만 본인 리뷰 수정은 다른 GET 요청이 실패해서 시도해보지 못했네요

/reviews GET 요청도 400에러 811 (유효하지 않은 양식의 reviews content) 응답하네요
