### ISSUE TITLE
태그 메인 페이지 API 요청.

### ISSUE THREAD

**Issue by chanhihi** [jiphyeonjeon-42/backend#582]
### 제안 설명

메인화면 한 컴포넌트에서 보여 줄 이유로 pagination은 필요 없다고 생각하지만, 혹시 나중을 생각하셔서 넣어 두는 것은 자율로 맡기겠습니다.

우선 현재 보내는 querystring은 limit=100&page=0&visibility=public으로 요청하는 상태이긴 합니다.

메인화면 특성상 visibility가 public인 친구들만 넘겨주시면 될 것 같습니다.

content가 중복이 되면 걸러서 보내주시면 될 것 같습니다. (검색시 동일하게 들어갈 것이기 때문에.)

해당하는 content가 super인지 sub인지 확인하는 요소가 필요합니다.

super type의 경우에는 해당 supertag에 달려있는 subtag의 **개수**가 필요합니다.
*(subtag라면 해당 count = 0)

``` json
{
  "items": [
    {
      "createdAt": "2023-04-12",
      "content": "1서클 추천 책",
      "type": "super",
      "count": 3
    },
    {
      "createdAt": "2023-04-12",
      "content": "chanheki 추천 책",
      "type": "default",
      "count": 0
    },
    {
      "createdAt": "2023-04-13",
      "content": "yena가_추천하는",
      "type": "default"
      "count": 0,
    },
    {
      "createdAt": "2023-04-13",
      "content": "python",
      "type": "super"
      "count": 5,
    }
  ]
}
```

**Comment by nyj001012** [comment]
혹시 정렬 순위는 있나요? 자칫하면 100개만 골라온다 했을 때, DB 데이터가 superTag -> defaultTag 순으로 정렬이 되면 superTag만 보일 가능성이 있어서요

**Comment by chanhihi** [comment]
정렬순위는 안두고 랜덤이면 좋을것 같긴한데.. 어떤식으로 하는게 좋을까요? 세부로직은 일임 하겠습니다!

**Comment by nyj001012** [comment]
그러면 가져올 때마다 랜덤한 순서로 들고 오게 하겠습니다 :)

**Comment by scarf005** [comment]
super태그 배열과 default 태그 배열을 따로 주면 어떨까요?
```json
{
	"super": [ ... ],
	"default": [ ... ]
}
```

**Comment by chanhihi** [comment]
super Tag와 default Tag의 content가 겹칠경우 super Tag를 우선시해서 가져 오는걸로 땅땅땅
고생하십쇼. 🙏

**Comment by nyj001012** [comment]
> super태그 배열과 default 태그 배열을 따로 주면 어떨까요?
> ```json
> {
> 	"super": [ ... ],
> 	"default": [ ... ]
> }
> ```

슈퍼랑 디폴트 구분 없이 이루어지는 작업이라 구분은 하지 않아도 될 것 같아요. 피드백 주셔서 감사합니다 :)
