### ISSUE TITLE
http://localhost:3000/docs/ 404 Error

### ISSUE THREAD

**Issue by nyj001012** [jiphyeonjeon-42/backend#648]
### 재현 방법

pnpm dev 후 http://localhost:3000/docs/ 에 접속하면 404 에러 발생
develop 브랜치, 599번 pr 브랜치에서도 똑같은 현상있음 

### 추가 정보

로그: `2023-08-06 23:28:04:284 http: GET /docs/ 404 144 - 2.478 ms`

**Comment by scarf005** [comment]
#640 PR에서 nginx 오류를 해결하며 경로를 `/swagger-v2`로 바꾸었는데, 공지가 부족했던 것 같습니다. 변경 경로에 대한 공식 문서는 https://jiphyeonjeon-42.github.io/backend/explanation/#v2_1 에서 확인 가능합니다.
