### ISSUE TITLE
backend Dockerfile빌드 오류

### ISSUE THREAD

**Issue by weg901127** [jiphyeonjeon-42/backend#763]
### 재현 방법

1.  backend컨테이너의 Dockerfile을 빌드합니다.
2. 빌드 과정중 pnpm 실행시 오류 발생

```[tasklist]
### Tasks
```

**Comment by scarf005** [comment]
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/ebb46472-c7b1-47f2-a2c1-32cce54b1eb9)

혹시 오류 메시지를 올려주실수 있을까요? 현재 `develop` 브랜치에서 `docker compose build --no-cache backend` 명령어를 통해 백엔드를 빌드하였으나 재현이 불가능합니다.

**Comment by weg901127** [comment]
<img width="1409" alt="스크린샷 2023-09-08 오후 5 06 01" src="https://github.com/jiphyeonjeon-42/backend/assets/19397975/445ee563-1e47-4a69-9973-6ccebb3fbe6b">

요런 오류요!
