### ISSUE TITLE
🚨관리자 로그인이 됩니다.🚨

### ISSUE THREAD

**Issue by seo-wo** [jiphyeonjeon-42/backend#813]
### 재현 방법

1. https://42library.kr 접속
2. 주소창에 https://42library.kr 뒤에 `/auth` 입력
3. jwoo님 계정으로 로그인됩니다. (아마 id: 1)

### 추가 정보

<img width="676" alt="Screenshot 2024-01-10 at 12 00 42 AM" src="https://github.com/jiphyeonjeon-42/backend/assets/82714924/5fa7eac9-1148-4eae-90f1-3de6efd42c1c">

대출 및 도서, 유저정보 수정 등은  되지 않으나 유저정보 및 도서 정보가 보입니다.

**Comment by jimin52** [comment]
## 원인 분석
**한줄요약: 로그인이 되는건 아님**
프론트에서 42library/auth 경로로 이동하면 백엔드의 `/auth/me` api 를 호출.
`auth/me` 요청에 인자가 없으면 1번 유저(jwoo)의 정보를 리턴함. (이것은 문제가 맞음. service 에 null 체크 로직 추가 필요.)
그러나 토큰을 발급하는 것은 아님. 그래서 jwt 권한이 필요한 api 들에는 접근이 되지 않음.
그러나 `user/search` api 의 권한이 막혀있지 않음. (이것도 문제임. `users/search` 에 권한 체크 미들웨어 추가 필요)

## 이슈 정리
1. `auth/me` api 는 인자가 없을경우 1번 유저 반환함
2. `users/search` api 에서 권한체크를 안함. 

## 해결책
1. `auth/me` api 에 인자 null 체크로직 추가
2. `users/search` 에 권한체크 미들웨어 추가

@nyj001012 제가 현재 서버 배포가 어떻게 되고있는지 잘 몰라서 관련 설정 공유 혹은 이슈 해결 부탁드립니다

**Comment by nyj001012** [comment]
> ## 원인 분석
> **한줄요약: 로그인이 되는건 아님**
> 프론트에서 42library/auth 경로로 이동하면 백엔드의 `/auth/me` api 를 호출.
> `auth/me` 요청에 인자가 없으면 1번 유저(jwoo)의 정보를 리턴함. (이것은 문제가 맞음. service 에 null 체크 로직 추가 필요.)
> 그러나 토큰을 발급하는 것은 아님. 그래서 jwt 권한이 필요한 api 들에는 접근이 되지 않음.
> 그러나 `user/search` api 의 권한이 막혀있지 않음. (이것도 문제임. `users/search` 에 권한 체크 미들웨어 추가 필요)
> 
> ## 이슈 정리
> 1. `auth/me` api 는 인자가 없을경우 1번 유저 반환함
> 2. `users/search` api 에서 권한체크를 안함. 
> 
> ## 해결책
> 1. `auth/me` api 에 인자 null 체크로직 추가
> 2. `users/search` 에 권한체크 미들웨어 추가
> 
> @nyj001012 제가 현재 서버 배포가 어떻게 되고있는지 잘 몰라서 관련 설정 공유 혹은 이슈 해결 부탁드립니다

서버 현재 수동 배포중이라... 오늘 내일 내로 해결해 두겠습니다
